### ISSUE TITLE
CopyCraftFile bugs launch clamps/staging

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#398]
Tested this but I see nothing in the log. Strange. 

When an active contract contains BEHAVIOR CopyCraftFile with option set to CONTRACT_ACCEPTED, the craft gets copied as you'd expect, the contract loads as you would expect.

However after launching from VAB any craft (not just this space shuttle example that gets copied) the staging is frozen after the first stage is fired.

Remove the Behavior from the contract, and craft staging works fine. Even for the same copied craft (if you keep it after cancelling the first attempt).

Contract:
https://github.com/inigmatus/GAP/blob/master/STS-1.cfg

Craft:
https://github.com/inigmatus/GAP/blob/master/Assets/Space%20Shuttle%20Intrepid.craft

no mods of course. CC only. I couldn't find anything happening in the logs though. Really really strange. I'll keep testing.

This also happens for other CopyCraftFile onState attributes such as CONTRACT_SUCCESS

**Comment by inigmatus** [comment]
Log file:  https://github.com/inigmatus/GAP/blob/master/Development/Bug398log

not sure what's happening. let me know if you can reproduce it.

**Comment by inigmatus** [comment]
I tested CONTRACT_SUCCESS, same thing. If you have an active contract with CopyCraftFile as a BEHAVIOUR node, any craft launched from VAB loses second stage capability.

**Comment by jrossignol** [comment]
Search for "[EXC" or Exception in the logs - those are usually the culprits.  In this case:
```
[EXC 15:39:03.671] NullReferenceException: Object reference not set to an instance of an object
	ContractConfigurator.Behaviour.TriggeredBehaviour.OnParameterStateChange (Contracts.ContractParameter param)
	ContractConfigurator.ContractBehaviour.ParameterStateChange (Contracts.ContractParameter param)
	ContractConfigurator.ConfiguredContract.OnParameterStateChange (Contracts.ContractParameter param)
	ContractConfigurator.ConfiguredContract.OnParameterStateChange (Contracts.Contract contract, Contracts.ContractParameter param)
	EventData`2[Contracts.Contract,Contracts.ContractParameter].Fire (Contracts.Contract data0, Contracts.ContractParameter data1)
	ContractConfigurator.Parameters.VesselParameter.CheckVessel (.Vessel vessel, Boolean forceStateChange)
	ContractConfigurator.Parameters.OrbitParameter.OnUpdate ()
	Contracts.ContractParameter.Update ()
	Contracts.Contract.Update ()
	Contracts.ContractSystem.UpdateContracts ()
	Contracts.ContractSystem+
	.MoveNext ()
```
I'll see what the problem is and put a fix together.

**Comment by jrossignol** [comment]
Fixed for 1.9.1

**Comment by inigmatus** [comment]
Awesome! One major step closer to doing a test STS contract. Thanks nightingale!

**Comment by inigmatus** [comment]
Not fixed.  Now currently the behavior cancels the contract after contract acceptance, or game load.


Here's a test contract:

CONTRACT_TYPE
{
//REQUIREMENTS FOR CONTRACT TO APPEAR


//DATA NODES TO PROCESS FOR CONTRACT USE


//CONTRACT DESCRIPTION
	name = Issue398
	title = Issue #398

	description = Description of bug.
	synopsis = Test the bug.
	completedMessage = You have tested the bug.
	
	maxSimultaneous = 1
	
	advanceFunds = 10000000
	rewardScience = 100000
	rewardReputation = 10000


//BEHAVIORS TO DO WHEN CREATING CONTRACT

	BEHAVIOUR
	{
		name = CopyCraftFile
		type = CopyCraftFile
		
		url = ContractPacks/GAP/Assets/Space Shuttle Intrepid.craft
		craftType = VAB
		onState = CONTRACT_ACCEPTED
		
	}


//PARAMETERS FOR CONTRACT COMPLETION

	PARAMETER
	{
		name = ReachState
		type = ReachState
		title = Get moving
		situation = LANDED
		minSpeed = 5.0
		targetBody = Kerbin
		
	}
	
}

**Comment by jrossignol** [comment]
Sorry, forgot to mention that old faces are likely broken on this one -
clear out old contacts completely and let me know if that works.

**Comment by inigmatus** [comment]
not yet. something still amiss...  I get this when clearing all active and archived contracts, fresh game. and accept the contract:

Exception occured while saving contract 'Issue398':
System.ArgumentException: Missing required value 'onState'.
  at ContractConfigurator.ConfigNodeUtil.ParseValue[State] (.ConfigNode configNode, System.String key, Boolean allowExpression) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.Behaviour.TriggeredBehaviour.OnLoad (.ConfigNode configNode) [0x00000] in <filename unknown>:0

**Comment by jrossignol** [comment]
My turn for a derpy moment past my bed time - I reversed OnSave and OnLoad.  Now it's actually fixed.

**Comment by inigmatus** [comment]
now you gone and done it. broke KSP.  loaded new career... get

Exception occured while saving contract 'Issue398':
System.NullReferenceException: Object reference not set to an instance of an object
  at ContractConfigurator.Behaviour.TriggeredBehaviour.OnSave (.ConfigNode configNode) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.Behaviour.CopyCraftFile.OnSave (.ConfigNode configNode) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.ContractBehaviour.Save (.ConfigNode configNode) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.ConfiguredContract.OnSave (.ConfigNode node) [0x00000] in <filename unknown>:0

**Comment by jrossignol** [comment]
Sorry, this was supposed to be a trivial fix and I'm unable to start KSP at the moment, so I thought I could sneak it through...  last time, try it again! :wink:

**Comment by inigmatus** [comment]
lol ok.  testing...

**Comment by inigmatus** [comment]
Fixed. You can go sleep in peace now. :D

**Comment by inigmatus** [comment]
um. contract accepted. alt f12 shows accepted, but now no contract loading in contract window...

**Comment by jrossignol** [comment]
Need logs - could be exception, could be stock app stupid stuff.

**Comment by inigmatus** [comment]
log: https://github.com/inigmatus/GAP/blob/master/Development/Issue398log

**Comment by jrossignol** [comment]
Sorry, confused now, since the edit on your post above (I think it was an edit) is different than what I got in the email.  Is it working or not?  Looking at the log it looks good, the very last line is:
```
[LOG 23:05:39.807] [DEBUG] ContractConfigurator.Behaviour.CopyCraftFile: Copying from 'C:/Users/Administrator/Downloads/KSP/KSP_win_DEV/KSP_Data/../\GameData\ContractPacks\GAP\Assets\Space Shuttle Intrepid.craft' to 'C:/Users/Administrator/Downloads/KSP/KSP_win_DEV/KSP_Data/../\saves\Development\Ships\VAB\Space Shuttle Intrepid.craft'.
```
Which is a good thing.

**Comment by inigmatus** [comment]
I deleted my working comment. I tested with a contract with the behaviour commented out. false pass.

testing with: 

CONTRACT_TYPE
{
//REQUIREMENTS FOR CONTRACT TO APPEAR

//DATA NODES TO PROCESS FOR CONTRACT USE

//CONTRACT DESCRIPTION
name = Issue398
title = Issue #398

description = Description of bug.
synopsis = Test the bug.
completedMessage = You have tested the bug.

maxSimultaneous = 1

advanceFunds = 10000000
rewardScience = 100000
rewardReputation = 10000
//BEHAVIORS TO DO WHEN CREATING CONTRACT

BEHAVIOUR
{
    name = CopyCraftFile
    type = CopyCraftFile

    url = ContractPacks/GAP/Assets/Space Shuttle Intrepid.craft
    craftType = VAB
    onState = CONTRACT_ACCEPTED

}
//PARAMETERS FOR CONTRACT COMPLETION

PARAMETER
{
    name = ReachState
    type = ReachState
    title = Get moving
    situation = LANDED
    minSpeed = 5.0
    targetBody = Kerbin

}
}



which when accepted, produces the log above... which doesn't indicate why the contract status window shows completely blank, even though AltF12 Contracts shows it accepted.  Again directly related to Behavior SpawnCraftFile.  The craft is copying fine. Always did.

**Comment by inigmatus** [comment]
new log showing issue I think:

[LOG 23:15:24.863] [DEBUG] ContractConfigurator.ConfiguredContract: Initializing contract: CONTRACT_TYPE [Issue398]
[ERR 23:15:24.865] Input is null

**Comment by inigmatus** [comment]
i just now updated the full log: https://github.com/inigmatus/GAP/blob/master/Development/Issue398log

**Comment by inigmatus** [comment]
Further testing reveals if I change state to tracking center and flip back to KSC view, the contract window populates with the accepted contract that has the Behaviour SpawnCraftFile.  If I reload the game/save same thing.

**Comment by jrossignol** [comment]
Worked as normal for me.  The stock contract window can be troublesome sometimes, especially when you're clearing contracts through the debug window.

Also, input is null is a red herring, it's a warning from the stock config node code.

**Comment by inigmatus** [comment]
Ill test with a new career...

**Comment by inigmatus** [comment]
Yup. I confirmed. Working normal there as well. I accepted by STS-1 Contract, and it loaded in KSC contract window fine. Launched. dream.  Ok. now you can sleep in peace. :D (and this time I double checked to make sure I wasn't commented out). Thanks nightingale!

**Comment by inigmatus** [comment]
I'm sorry to bring it back up. CopyCraftFile is still bugged, and after my testing, this does not appear to be a contract window issue where the actual contract not being fully loaded or read somehow, caused by the CopyCraftFile behaviour.

I tested this by adding a SpawnPassengers behaviour, and a HasPassengers parameter to the Issue398 config file to see if it was merely a contract window issue not simply being refreshed. It wasn't. The contract simply isn't being fully loaded until there is a change state to Tracking Station or runway or launch pad - which of course is too late to load any SpawnPassengers behaviour and thus complete the contract.

Here are my files I tested with, steps, and a verbose log:

Issue398.cfg: https://github.com/inigmatus/GAP/blob/master/Development/Issue398.cfg
craft file: https://github.com/inigmatus/GAP/blob/master/Assets/Space%20Shuttle%20Intrepid.craft

Duplication Steps:

1. Start new career
2. Accept Issue398 contract
3. Verify in KSC view the contract and its parameters load (contract window populated)
4. Verify in Astronaut Complex (or SPH or VAB or KSC view load from runway or launch pad) the tourist appears on roster
5. Go to Mission Control and cancel the active Issue398 contract.
6. Verify in KSC view the canceled contract and its parameters are removed (contract window blank)
7. Go to Mission Control and accept new Issue398 contract (I toggled to Tracking Station and back to Mission Control to regenerate the contract)
*8. Verify in KSC view the new Issue398 contract and its parameters are missing (contract window blank)
9. Verify in Mission Control that Issue398 is an Active Contract
*10. Verify in Astronaut Complex (or SPH or VAB or KSC view load from runway or launch pad) that the tourist does not appear on the roster. (this indicates to me this is NOT a contract window issue)
11. Toggle to Tracking Station and back to KSC view
12. Verify in KSC view the new Issue398 contract and its parameters load (contract window populated)
*13. Verify in Astronaut Complex (or SPH or VAB or KSC view load from runway or launch pad) that the tourist still does not appear on the roster. The contract is still thus unable to complete.

* is the issue

VERBOSE log file of the above steps:

https://raw.githubusercontent.com/inigmatus/GAP/master/Development/Issue398.log

Conclusion:
This seems like it might be a critical issue since it also means any other subsequent contracts with CopyCraftFile will be affected (in that once a contract with CopyCraftFile is loaded initially, whether completed or not, any subsequent CopyCraftFile contract will not load at all until a change state occurs, which is too late in contracts expecting to process additional behaviours such as SpawnPassengers),

I though I'd make this one easier to troubleshoot since we've been working on this one for a while now and this time I didn't want to cut any corners in my reporting. :D

**Comment by jrossignol** [comment]
Re-opening

**Comment by jrossignol** [comment]
Looks like this would be it:
```
[EXC 00:38:48.186] IOException: C:/Users/Administrator/Downloads/KSP/KSP_win_DEV/KSP_Data/../\saves\default\Ships\VAB\Space Shuttle Intrepid.craft already exists
	System.IO.File.Copy (System.String sourceFileName, System.String destFileName, Boolean overwrite)
	System.IO.File.Copy (System.String sourceFileName, System.String destFileName)
	ContractConfigurator.Behaviour.CopyCraftFile.TriggerAction ()
	ContractConfigurator.Behaviour.TriggeredBehaviour.OnAccepted ()
	ContractConfigurator.ContractBehaviour.Accept ()
	ContractConfigurator.ConfiguredContract.OnAccepted ()
	Contracts.Contract.SetState (State newState)
	Contracts.Contract.Accept ()
	MissionControl.BtnInputAccept (.POINTER_INFO& ptr)
	UIButton.OnInput (.POINTER_INFO& ptr)
	AutoSpriteControlBase.OnInput (POINTER_INFO ptr)
	UIManager.DispatchHelper (.POINTER_INFO& curPtr, Int32 camIndex)
	UIManager.DispatchInput ()
	UIManager.Update ()
	UIManager.DidAnyPointerHitUI ()
	SpaceCenterCamera2.InputCamera ()
	SpaceCenterCamera2.Update ()
```

**Comment by jrossignol** [comment]
Please give this one another retest.

**Comment by inigmatus** [comment]
Confirmed fixed. All the above scenarios pass now. Thanks.
