### ISSUE TITLE
PartValidation NONE node applying check against all FILTER objects, not just those with matching attributes in the NONE node.

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#449]
from: http://forum.kerbalspaceprogram.com/index.php?/topic/91625-105-contract-configurator-v1931-2016-01-11/&do=findComment&comment=2364310

essentially I want to limit a player's valid craft to having any engine type except solid rocket motors.

		PARAMETER
		{
			name = PartValidation
			type = PartValidation
			title = not have any solid rocket motors
			
			FILTER
			{
				partModule = ModuleEngines
			}

			NONE
			{
				MODULE
				{
				    EngineType = SolidBooster
				}
			}
		}
```
simply fails to pass any engine types, regardless if its classified as a SolidBooster.

**Comment by jrossignol** [comment]
There was a problem with how the min/max count was defaulting which was messing things up.  I've fixed that and now the parameter shows the text I would've expected.  I didn't follow through with the testing, but it doesn't work as expected raise a new bug please and I'll take a look.

Fixed for 1.9.4

**Comment by inigmatus** [comment]
Still not working or displaying as expected.

    PARAMETER
    {
        name = PartValidation
        type = PartValidation
        title = not have any solid rocket motors

        FILTER
        {
            partModule = ModuleEngines
        }

        NONE
        {
            MODULE
            {
                EngineType = SolidBooster
            }
        }
    }

for the above code, the contract window shows:

not have any solid rocket motors:
  With module: Engines: Incomplete
  None have module with: Incomplete
    None have Engine Type: SolidBooster: Incomplete

For some reason the MODULE node itself is being checked against itself creating the empty

  None have module with: Incomplete

check which obviously will fail any part with partModule = ModuleEngines

**Comment by jrossignol** [comment]
Look at the hierarchy - that is correct. On phone, will give more details
later if necessary.

**Comment by inigmatus** [comment]
The code above though fails all engines: liquid, solid, and jet.

**Comment by inigmatus** [comment]
Is my code example correct? Do you know what code I should be using to exclude engines with solids?

**Comment by jrossignol** [comment]
Looks correct to me.

**Comment by inigmatus** [comment]
After more testing, I think it's a problem with CC not recognizing EngineType?

After all, this works:

		PARAMETER
		{
			name = PartValidation
			type = PartValidation

            FILTER
            {
                MODULE
                {
                    experimentID = mysteryGoo
					
                }
            }

            minCount = 1
			
		}

and accurately validates if i have a goo canister. 

but this does not:

		PARAMETER
		{
			name = PartValidation
			type = PartValidation

            FILTER
            {
                MODULE
                {
                    EngineType = SolidBooster
					
                }
            }

            minCount = 1
			
		}

**Comment by jrossignol** [comment]
Open new issue, I'll take a look tomorrow.
